# Aula 02 - Python
## Dados numéricos

In [16]:
# Variável inteira
a = 1
print('Valor de a = '+str(a))
type(a) 
# No exemplo acima, "a" é uma variável inteira que, no comando print, foi convertida em texto pelo uso do "str"/string.
# type(a) mostra o tipo de variável de a.

Valor de a = 1


int

In [4]:
# Variável dupla precisão
b = 1.0
print(b)
type(b)
# Variáveis do tipo float são mais precisas, porém podem pesar no código, por isso devem ser usadas somente quando necessário.

1.0


float

In [6]:
# Converter float para int
c = int(b)
print(c)
type(c)
#A variável c foi definida como o valor inteiro b.

1


int

In [13]:
# Delacrando nan
import numpy as np
d = np.nan
print(d)
type(d)

# Operação com NaN
e = d*1
print(e)
e = d+1
print(e)
e = np.nansum([d,1])
print(e)

nan
nan
nan
1.0


## Dados de texto 

In [18]:
# Declaração de variável texto
f = 'Fábio'
g = "Gabriel"
print(f)
print(g)
print(f+g)
print(f+' '+g)
#Nesse exemplo, foram ilustradas as variáveis de texto e como no comando print é preciso especificar os espaços entre uma palavra e outra.

Fábio
Gabriel
FábioGabriel
Fábio Gabriel


## Dados tipo bool - lógica

In [21]:
a==1

True

In [24]:
h = (a==1)
print(h)
type(h)

True


bool

In [26]:
h = (a==2)
print(h)
type(h)

False


bool

In [28]:
i = True
type(i)

bool

In [30]:
ii = 'True'
type(ii)

str

In [32]:
# Nos exemplos acima, foram explorados os dados tipo bool, dados de lógica. A variável "a" já havia sido definida como a=1, logo afirmar que o valor numérico de a é 1 (a==1) é verdadeiro/True.
# No exemplo, também foi feita a distinção entre True (variável bool) e "True", entre aspas, (variável de texto/string).

### Operação de comparação

In [36]:
# Operação ==
a==b
# igual

True

In [38]:
# Operação ><
a>b
# maior, menor

False

In [41]:
# Operação !=
a!=b
# diferente

False

In [43]:
# Operação >= ou <=
a>=b
#maior/menor ou igual

True

## Operações matemáticas

In [46]:
# Soma 
a+b

2.0

In [48]:
# Soma e atribui valor
ab = a+b
print(ab)
#Aqui foi criada a variável ab para representar a soma de a e b.

2.0


In [50]:
# Multiplicação
l = a*b # Não use l como variável
print("Não use l como nome de variável")
j = a*b
print(j)

Não use l como nome de variável
1.0


In [52]:
# Divisão
a/b

1.0

In [54]:
# Potencia
5**2

25

In [56]:
# Operações matemáticas com a bibliotéca math
import math

math.exp(10)
# Aqui foi importada a biblioteca math. Para usar seus recursos, é preciso escrever "math.recurso".

22026.465794806718

In [58]:
math.exp(0)

1.0

In [60]:
math.exp(a)

2.718281828459045

In [62]:
math.exp(-10)

4.5399929762484854e-05

In [64]:
import math as mt
mt.log(c)
# A biblioteca foi importada como no caso anterior, porém foi atribuído o nome mt. Portanto, para usá-la, é preciso escrever "mt.função".

0.0

In [66]:
mt.log10(100)

2.0

## Listas

In [69]:
myFirstList = [1,2,3]
print(myFirstList)
# Listas são como vetores, apresentados entre colchetes.

[1, 2, 3]


In [71]:
# Acessando valores da lista pelo index
print(myFirstList[0])
print(myFirstList[2])
# Os itens de uma lista são dispostos sequencialmente: [0, 1, ..., n]. É possível acessar o enésimo item da lista como no exemplo: 
# NomeDaLista[index/posição do elemento]

1
3


In [73]:
myFirstList==a

False

In [75]:
myFirstList[0]==a
# O primeiro item da lista é igual à variável "a", definida anteriormente. 

True

In [78]:
mySecList = [1,a,'c']
print(mySecList)

[1, 1, 'c']


In [80]:
type(mySecList)

list

In [82]:
type(mySecList[2])

str

In [84]:
type(mySecList[1])

int

## Caminhos = path

In [14]:
path = r"C:\Users\Leonardo.Hoinaski\Documents\ENS410064_1"
print(path)

C:\Users\Leonardo.Hoinaski\Documents\ENS410064_1


In [16]:
path = "C:/Users/Leonardo.Hoinaski/Documents/ENS410064_1"
print(path)

C:/Users/Leonardo.Hoinaski/Documents/ENS410064_1


In [21]:
import os
# Listar arquivos na pasta
# os.listdir(path)
# lista os arquivos da pasta

In [ ]:
# Selecionar primeiro arquivo listado
# os.listdir(path)[0]

In [23]:
# Concatenando caminhos
# path+"/"+os.listdir(path)[0] 
# Vai imprimir path/primeiro item 

In [25]:
# Listando caminho concatenado
# os.listdir(path+"/"+os.listdir(path)[0])
# A concatenação é a união de elementos (neste caso o caminho path e o 1° elemento da lista)
# Nesse exemplo, vai imprimir uma lista dos arquivos da pasta ".git"

In [28]:
# Diretório que estou trababalhando
os.getcwd()

'/home/2f263490-d72c-4651-993f-4fd00a2600b5'

In [30]:
# Mudo de diretório para o caminho 
# os.chdir('C:\\Users\\Leonardo.Hoinaski\\Documents\\')

In [48]:
# Criando diretório
new_path = os.getcwd()+'/test'

if os.path.isdir(new_path):
    print('diretório já existe')
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path) 
    
"""
Foi definido o caminho new_path como "diretório que estou trabalhando"/test
Se o diretório test já existisse, a saída seria "diretório já existe"
Caso contrário, seria usado o mkdir para criá-lo.
"""

diretório já existe


'\nFoi definido o caminho new_path como "diretório que estou trabalhando"/test\nSe o diretório test já existisse, a saída seria "diretório já existe"\nCaso contrário, seria usado o mkdir para criá-lo.\n'

In [ ]:
"""
# Criando diretório
new_path = os.getcwd()+'/test2'

if os.path.isdir(new_path):
    print('diretório já existe')
    # Criando um arquivo de texto
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")
else:
    print('Criando diretório '+new_path)
    os.mkdir(new_path)
    with open(new_path+"/copy.txt", "w") as file:
        file.write("Your text goes here")
"""

## Numpy arrays e Pandas DataFrames


In [54]:
import numpy as np
# Criando uma variável numpy
n = np.array(0)
type(n)

numpy.ndarray

In [67]:
# Criando uma variável numpy a partir de uma lista
myThirdList=[1,2,3,10,20,55]
n = np.array(myThirdList)
print(n)
# foi criada uma lista, a qual foi armazenada na variável n, um array, com o auxílio da biblioteca numpy.

[ 1  2  3 10 20 55]


In [208]:
# Criando uma matriz de 10x10 de números aleatórios entre 0 e 1
n = np.random.rand(10,10) # OBS: estamos sempre usando os recursos da biblioteca numpy
print(n)
# Dimensões da matrix
print("\n", n.shape)

[[0.10363052 0.0305267  0.20698301 0.05790364 0.564593   0.30495746
  0.23253499 0.86051853 0.14983506 0.36793227]
 [0.04316712 0.42724643 0.44159897 0.9635555  0.86536513 0.35199351
  0.11682371 0.86179341 0.22672133 0.93578898]
 [0.99190183 0.77463728 0.18437478 0.82132744 0.65662268 0.37654773
  0.23438368 0.85941857 0.92511088 0.76667614]
 [0.72854639 0.57054161 0.30242775 0.41387129 0.09988509 0.54151097
  0.45308753 0.83431622 0.92966894 0.63086013]
 [0.09615511 0.58982827 0.26591397 0.12903801 0.52699193 0.97110211
  0.84965994 0.07314664 0.89899495 0.75489853]
 [0.11719153 0.51564762 0.31025044 0.3328     0.21385791 0.76908437
  0.95845479 0.07468885 0.46290841 0.18334422]
 [0.2412452  0.18323752 0.13773617 0.24958919 0.40732329 0.03992051
  0.12207378 0.70617865 0.95432841 0.57192057]
 [0.41715992 0.43042743 0.87098858 0.00880762 0.22411651 0.06240835
  0.28469302 0.87519727 0.81091206 0.02792653]
 [0.25893693 0.6689368  0.73474592 0.95180351 0.11201421 0.05557235
  0.55067933

In [210]:
# Acessando valores da matriz
n[0,:]  #Acessa todos os elementos da primeira linha 

array([0.10363052, 0.0305267 , 0.20698301, 0.05790364, 0.564593  ,
       0.30495746, 0.23253499, 0.86051853, 0.14983506, 0.36793227])

In [212]:
n[:,1:5] #Acessa todas as linhas, das colunas 1 a 4

array([[0.0305267 , 0.20698301, 0.05790364, 0.564593  ],
       [0.42724643, 0.44159897, 0.9635555 , 0.86536513],
       [0.77463728, 0.18437478, 0.82132744, 0.65662268],
       [0.57054161, 0.30242775, 0.41387129, 0.09988509],
       [0.58982827, 0.26591397, 0.12903801, 0.52699193],
       [0.51564762, 0.31025044, 0.3328    , 0.21385791],
       [0.18323752, 0.13773617, 0.24958919, 0.40732329],
       [0.43042743, 0.87098858, 0.00880762, 0.22411651],
       [0.6689368 , 0.73474592, 0.95180351, 0.11201421],
       [0.69607189, 0.95315283, 0.29434533, 0.03102987]])

In [214]:
n[0,1:5] #acessa, na primeira linha, os elementos das colunas 1 a 4

array([0.0305267 , 0.20698301, 0.05790364, 0.564593  ])

In [217]:
n[0,-1] # acessa o último elemento da primeira linha 

0.36793226722627037

In [219]:
an = np.log(n*5)
print(an)

[[-0.65748546 -1.87971566  0.03431934 -1.23953711  1.03778775  0.42185491
   0.15072336  1.45921778 -0.28878225  0.6095815 ]
 [-1.53323837  0.75904359  0.79208479  1.57231273  1.46483417  0.56529538
  -0.53765135  1.46069821  0.12540429  1.54307263]
 [ 1.60130678  1.35407753 -0.08134684  1.41260449  1.18879218  0.63272745
   0.15864205  1.45793871  1.53159624  1.34374711]
 [ 1.29273393  1.04826873  0.41352505  0.72723767 -0.69429698  0.99604596
   0.81776796  1.42829512  1.53651118  1.1487668 ]
 [-0.73235478  1.08151407  0.28485546 -0.43821038  0.96886787  1.58011426
   1.44651883 -1.00585112  1.50296005  1.32826597]
 [-0.53450775  0.94710626  0.43906247  0.50922433  0.06699444  1.34688331
   1.56700503 -0.9849865   0.83921185 -0.086952  ]
 [ 0.18749647 -0.08753416 -0.37297729  0.22149896  0.71128982 -1.61142722
  -0.49369172  1.26155088  1.56269049  1.05068275]
 [ 0.73515227  0.76646136  1.4713115  -3.12269958  0.11384868 -1.16461833
   0.3530941   1.47613195  1.39984225 -1.96874017]


In [233]:

def imprime_matriz(matriz):
    for linha in matriz:
        for elemento in linha:
            print(f"{elemento:7}", end=" ")  # Formatação com 7 espaços
        print()  # Pula para a próxima linha

m = ([f"{elemento:.2f}" for elemento in linha] for linha in an) # limita para duas casas decimais
print(imprime_matriz(m))

-0.66   -1.88   0.03    -1.24   1.04    0.42    0.15    1.46    -0.29   0.61    
-1.53   0.76    0.79    1.57    1.46    0.57    -0.54   1.46    0.13    1.54    
1.60    1.35    -0.08   1.41    1.19    0.63    0.16    1.46    1.53    1.34    
1.29    1.05    0.41    0.73    -0.69   1.00    0.82    1.43    1.54    1.15    
-0.73   1.08    0.28    -0.44   0.97    1.58    1.45    -1.01   1.50    1.33    
-0.53   0.95    0.44    0.51    0.07    1.35    1.57    -0.98   0.84    -0.09   
0.19    -0.09   -0.37   0.22    0.71    -1.61   -0.49   1.26    1.56    1.05    
0.74    0.77    1.47    -3.12   0.11    -1.16   0.35    1.48    1.40    -1.97   
0.26    1.21    1.30    1.56    -0.58   -1.28   1.01    0.19    1.30    0.45    
-0.54   1.25    1.56    0.39    -1.86   0.93    -0.02   0.48    0.38    1.18    
None
